# 애플리케이션을 배포할 App Server 목록 (공용 인프라)
[app_servers]
# VM 4: App Server 1
app1 ansible_host=1.201.118.202
# VM 5: App Server 2
app2 ansible_host=1.201.118.10
# VM 6: App Server 3
app3 ansible_host=1.201.118.90

[app_servers:vars]
# Jenkins Credential과 함께 사용할 App Server SSH 계정
ansible_user=taehyeon
