all:
  children:
    app_servers:
      hosts:
        dongwook_app1:
          ansible_host: 1.201.118.202
        dongwook_app2:
          ansible_host: 1.201.118.10
        dongwook_app3:
          ansible_host: 1.201.118.90
    load_balancers:
      hosts:
        dongwook_lb:
          ansible_host: 1.201.116.156
